name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker images
      run: |
        docker build --file src/LemonTree/LemonTree/Dockerfile --tag crgarlemontreeregistry.azurecr.io/lemontreeserver:${{github.run_number}} --tag crgarlemontreeregistry.azurecr.io/lemontreeserver:latest src/LemonTree 
    - name: Login to registry
      env:
        ContainerRegistryPassword: ${{ secrets.ContainerRegistryPassword }}
      run: docker login -u crgarlemontreeregistry -p "$ContainerRegistryPassword" crgarlemontreeregistry.azurecr.io
    - name: Push Docker images
      run: |
        docker push crgarlemontreeregistry.azurecr.io/lemontreeserver
        
  release:
    needs: build
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: Run Docker Image
      env:
        ContainerRegistryPassword: ${{ secrets.ContainerRegistryPassword }}
      run: |
        docker login -u crgarlemontreeregistry -p "$ContainerRegistryPassword" crgarlemontreeregistry.azurecr.io
        docker run crgarlemontreeregistry.azurecr.io/lemontreeserver:latest

