name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker images
      run: sudo docker build --file src/LemonTree/LemonTree/Dockerfile --tag crgarlemontreeregistry.azurecr.io/lemontreeserver:${{github.run_number}} --tag crgarlemontreeregistry.azurecr.io/lemontreeserver:latest src/LemonTree 
    - name: Login to registry
      env:
        ContainerRegistryPassword: ${{ secrets.ContainerRegistryPassword }}
      run: sudo docker login -u crgarlemontreeregistry -p "$ContainerRegistryPassword" crgarlemontreeregistry.azurecr.io
    - name: Push Docker images
      run: sudo docker push crgarlemontreeregistry.azurecr.io/lemontreeserver
        
  release:
    needs: build
    runs-on: self-hosted
    
    steps:
    - name: Run Docker Image
      env:
        ContainerRegistryPassword: ${{ secrets.ContainerRegistryPassword }}
      run: |
        sudo docker login -u crgarlemontreeregistry -p "$ContainerRegistryPassword" crgarlemontreeregistry.azurecr.io
        docker ps -aq --filter "name=lemontreeserver" | grep -q . && docker kill lemontreeserver && docker rm -fv lemontreeserver
        sudo docker run --rm -p 9999:80 --name=lemontreeserver -d crgarlemontreeregistry.azurecr.io/lemontreeserver:${{github.run_number}}

